export const userSchemas: any = {
  user01: {
    user_id: "user01",
    db_url: `/dvdrental`,
    schema: [
      {
        table_schema: "hdb_catalog",
        table_name: "event_invocation_logs",
        columns: [
          {
            column_name: "id",
            data_type: "text",
            is_nullable: "NO",
            column_default: "hdb_catalog.gen_hasura_uuid()",
          },
          {
            column_name: "trigger_name",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "event_id",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "status",
            data_type: "integer",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "request",
            data_type: "json",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "response",
            data_type: "json",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "created_at",
            data_type: "timestamp without time zone",
            is_nullable: "YES",
            column_default: "now()",
          },
        ],
      },
      {
        table_schema: "hdb_catalog",
        table_name: "event_log",
        columns: [
          {
            column_name: "id",
            data_type: "text",
            is_nullable: "NO",
            column_default: "hdb_catalog.gen_hasura_uuid()",
          },
          {
            column_name: "schema_name",
            data_type: "text",
            is_nullable: "NO",
            column_default: null,
          },
          {
            column_name: "table_name",
            data_type: "text",
            is_nullable: "NO",
            column_default: null,
          },
          {
            column_name: "trigger_name",
            data_type: "text",
            is_nullable: "NO",
            column_default: null,
          },
          {
            column_name: "payload",
            data_type: "jsonb",
            is_nullable: "NO",
            column_default: null,
          },
          {
            column_name: "delivered",
            data_type: "boolean",
            is_nullable: "NO",
            column_default: "false",
          },
          {
            column_name: "error",
            data_type: "boolean",
            is_nullable: "NO",
            column_default: "false",
          },
          {
            column_name: "tries",
            data_type: "integer",
            is_nullable: "NO",
            column_default: "0",
          },
          {
            column_name: "created_at",
            data_type: "timestamp without time zone",
            is_nullable: "YES",
            column_default: "now()",
          },
          {
            column_name: "locked",
            data_type: "timestamp with time zone",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "next_retry_at",
            data_type: "timestamp without time zone",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "archived",
            data_type: "boolean",
            is_nullable: "NO",
            column_default: "false",
          },
        ],
      },
      {
        table_schema: "hdb_catalog",
        table_name: "hdb_event_log_cleanups",
        columns: [
          {
            column_name: "id",
            data_type: "text",
            is_nullable: "NO",
            column_default: "hdb_catalog.gen_hasura_uuid()",
          },
          {
            column_name: "trigger_name",
            data_type: "text",
            is_nullable: "NO",
            column_default: null,
          },
          {
            column_name: "scheduled_at",
            data_type: "timestamp without time zone",
            is_nullable: "NO",
            column_default: null,
          },
          {
            column_name: "deleted_event_logs",
            data_type: "integer",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "deleted_event_invocation_logs",
            data_type: "integer",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "status",
            data_type: "text",
            is_nullable: "NO",
            column_default: null,
          },
        ],
      },
      {
        table_schema: "hdb_catalog",
        table_name: "hdb_source_catalog_version",
        columns: [
          {
            column_name: "version",
            data_type: "text",
            is_nullable: "NO",
            column_default: null,
          },
          {
            column_name: "upgraded_on",
            data_type: "timestamp with time zone",
            is_nullable: "NO",
            column_default: null,
          },
        ],
      },
      {
        table_schema: "public",
        table_name: "alerts",
        columns: [
          {
            column_name: "id",
            data_type: "uuid",
            is_nullable: "NO",
            column_default: "uuid_generate_v4()",
          },
          {
            column_name: "userid",
            data_type: "uuid",
            is_nullable: "NO",
            column_default: null,
          },
          {
            column_name: "created_by",
            data_type: "uuid",
            is_nullable: "NO",
            column_default: null,
          },
          {
            column_name: "created_at",
            data_type: "timestamp without time zone",
            is_nullable: "NO",
            column_default: "CURRENT_TIMESTAMP",
          },
          {
            column_name: "isread",
            data_type: "boolean",
            is_nullable: "NO",
            column_default: "false",
          },
          {
            column_name: "noteid",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "logbook_entry_id",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "comment_id",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "type",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "is_cleared",
            data_type: "boolean",
            is_nullable: "YES",
            column_default: "false",
          },
        ],
      },
      {
        table_schema: "public",
        table_name: "asset_events",
        columns: [
          {
            column_name: "id",
            data_type: "uuid",
            is_nullable: "NO",
            column_default: "uuid_generate_v4()",
          },
          {
            column_name: "asset_id",
            data_type: "uuid",
            is_nullable: "NO",
            column_default: null,
          },
          {
            column_name: "old_status",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "new_status",
            data_type: "text",
            is_nullable: "NO",
            column_default: null,
          },
          {
            column_name: "changed_at",
            data_type: "timestamp with time zone",
            is_nullable: "NO",
            column_default: "now()",
          },
          {
            column_name: "changed_by",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "notes",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
        ],
      },
      {
        table_schema: "public",
        table_name: "assets",
        columns: [
          {
            column_name: "id",
            data_type: "uuid",
            is_nullable: "NO",
            column_default: "uuid_generate_v4()",
          },
          {
            column_name: "name",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "location_id",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "type",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "isAssetActive",
            data_type: "boolean",
            is_nullable: "YES",
            column_default: "true",
          },
          {
            column_name: "textsearch",
            data_type: "tsvector",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "asset_status",
            data_type: "text",
            is_nullable: "YES",
            column_default: "'inService'::text",
          },
          {
            column_name: "asset_grouping",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
        ],
      },
      {
        table_schema: "public",
        table_name: "audit_trail",
        columns: [
          {
            column_name: "changeid",
            data_type: "uuid",
            is_nullable: "NO",
            column_default: "uuid_generate_v4()",
          },
          {
            column_name: "logbookentryid",
            data_type: "uuid",
            is_nullable: "NO",
            column_default: null,
          },
          {
            column_name: "noteid",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "changedby",
            data_type: "uuid",
            is_nullable: "NO",
            column_default: null,
          },
          {
            column_name: "changetype",
            data_type: "character varying",
            is_nullable: "NO",
            column_default: null,
          },
          {
            column_name: "changedetails",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "timestamp",
            data_type: "timestamp with time zone",
            is_nullable: "YES",
            column_default: "CURRENT_TIMESTAMP",
          },
        ],
      },
      {
        table_schema: "public",
        table_name: "comments",
        columns: [
          {
            column_name: "commentid",
            data_type: "uuid",
            is_nullable: "NO",
            column_default: "uuid_generate_v4()",
          },
          {
            column_name: "noteid",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "userid",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "commenttext",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "createdat",
            data_type: "timestamp with time zone",
            is_nullable: "YES",
            column_default: "now()",
          },
          {
            column_name: "updatedat",
            data_type: "timestamp with time zone",
            is_nullable: "YES",
            column_default: "now()",
          },
          {
            column_name: "tagged_users",
            data_type: "ARRAY",
            is_nullable: "YES",
            column_default: null,
          },
        ],
      },
      {
        table_schema: "public",
        table_name: "locations",
        columns: [
          {
            column_name: "id",
            data_type: "uuid",
            is_nullable: "NO",
            column_default: "uuid_generate_v4()",
          },
          {
            column_name: "name",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
        ],
      },
      {
        table_schema: "public",
        table_name: "logbook_entries",
        columns: [
          {
            column_name: "entryid",
            data_type: "uuid",
            is_nullable: "NO",
            column_default: "uuid_generate_v4()",
          },
          {
            column_name: "userid",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "assetid",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "timeframe",
            data_type: "timestamp with time zone",
            is_nullable: "YES",
            column_default: "CURRENT_TIMESTAMP",
          },
          {
            column_name: "type",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "priority",
            data_type: "integer",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "createdby",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "updatedby",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "location_id",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "logbook_id",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "textsearch",
            data_type: "tsvector",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "archive",
            data_type: "boolean",
            is_nullable: "YES",
            column_default: "false",
          },
          {
            column_name: "current_asset_status",
            data_type: "text",
            is_nullable: "YES",
            column_default: "'inService'::text",
          },
        ],
      },
      {
        table_schema: "public",
        table_name: "logbooks",
        columns: [
          {
            column_name: "id",
            data_type: "uuid",
            is_nullable: "NO",
            column_default: "uuid_generate_v4()",
          },
          {
            column_name: "name",
            data_type: "text",
            is_nullable: "NO",
            column_default: null,
          },
          {
            column_name: "created_by",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "location_id",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "created_at",
            data_type: "timestamp with time zone",
            is_nullable: "YES",
            column_default: "now()",
          },
          {
            column_name: "updated_at",
            data_type: "timestamp with time zone",
            is_nullable: "YES",
            column_default: "now()",
          },
        ],
      },
      {
        table_schema: "public",
        table_name: "notes",
        columns: [
          {
            column_name: "noteid",
            data_type: "uuid",
            is_nullable: "NO",
            column_default: "uuid_generate_v4()",
          },
          {
            column_name: "entryid",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "notetext",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "createdat",
            data_type: "timestamp with time zone",
            is_nullable: "YES",
            column_default: "now()",
          },
          {
            column_name: "createdby",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "lasteditedby",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "lastediteddate",
            data_type: "timestamp with time zone",
            is_nullable: "YES",
            column_default: "now()",
          },
          {
            column_name: "attachment_urls",
            data_type: "ARRAY",
            is_nullable: "YES",
            column_default: "'{}'::text[]",
          },
          {
            column_name: "textsearch",
            data_type: "tsvector",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "notetext_raw",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "tagged_users",
            data_type: "ARRAY",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "shift_id",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "note_asset_status",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
        ],
      },
      {
        table_schema: "public",
        table_name: "permissions",
        columns: [
          {
            column_name: "id",
            data_type: "uuid",
            is_nullable: "NO",
            column_default: "uuid_generate_v4()",
          },
          {
            column_name: "permission_name",
            data_type: "text",
            is_nullable: "NO",
            column_default: null,
          },
          {
            column_name: "title",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "description",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
        ],
      },
      {
        table_schema: "public",
        table_name: "prompt_ql_data",
        columns: [
          {
            column_name: "id",
            data_type: "uuid",
            is_nullable: "NO",
            column_default: "gen_random_uuid()",
          },
          {
            column_name: "data",
            data_type: "jsonb",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "status",
            data_type: "text",
            is_nullable: "NO",
            column_default: null,
          },
          {
            column_name: "fetched_at",
            data_type: "timestamp with time zone",
            is_nullable: "NO",
            column_default: "now()",
          },
          {
            column_name: "process_name",
            data_type: "character varying",
            is_nullable: "YES",
            column_default: null,
          },
        ],
      },
      {
        table_schema: "public",
        table_name: "refresh_status",
        columns: [
          {
            column_name: "status",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
        ],
      },
      {
        table_schema: "public",
        table_name: "report_content_details",
        columns: [
          {
            column_name: "content_id",
            data_type: "uuid",
            is_nullable: "NO",
            column_default: "uuid_generate_v4()",
          },
          {
            column_name: "shift_report_id",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "asset_grouping",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "created_by",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "created_at",
            data_type: "timestamp without time zone",
            is_nullable: "YES",
            column_default: "CURRENT_TIMESTAMP",
          },
          {
            column_name: "noteid",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "logbook_entry_id",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "asset_id",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
        ],
      },
      {
        table_schema: "public",
        table_name: "report_settings",
        columns: [
          {
            column_name: "id",
            data_type: "uuid",
            is_nullable: "NO",
            column_default: "uuid_generate_v4()",
          },
          {
            column_name: "sort_by",
            data_type: "character varying",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "asset_status",
            data_type: "ARRAY",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "show_passdown_by",
            data_type: "boolean",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "show_created_by",
            data_type: "boolean",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "created_at",
            data_type: "timestamp with time zone",
            is_nullable: "YES",
            column_default: "CURRENT_TIMESTAMP",
          },
          {
            column_name: "report_email_list",
            data_type: "ARRAY",
            is_nullable: "YES",
            column_default: null,
          },
        ],
      },
      {
        table_schema: "public",
        table_name: "report_shifts",
        columns: [
          {
            column_name: "shift_report_id",
            data_type: "uuid",
            is_nullable: "NO",
            column_default: "uuid_generate_v4()",
          },
          {
            column_name: "report_id",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "shift_id",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "time_frame",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "asset_id",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "shift_summary",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
        ],
      },
      {
        table_schema: "public",
        table_name: "reports",
        columns: [
          {
            column_name: "report_id",
            data_type: "uuid",
            is_nullable: "NO",
            column_default: "uuid_generate_v4()",
          },
          {
            column_name: "date",
            data_type: "date",
            is_nullable: "NO",
            column_default: null,
          },
          {
            column_name: "user_id",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "created_at",
            data_type: "timestamp without time zone",
            is_nullable: "YES",
            column_default: "CURRENT_TIMESTAMP",
          },
          {
            column_name: "status",
            data_type: "text",
            is_nullable: "YES",
            column_default: "'Generated'::text",
          },
        ],
      },
      {
        table_schema: "public",
        table_name: "role_permissions",
        columns: [
          {
            column_name: "id",
            data_type: "uuid",
            is_nullable: "NO",
            column_default: "gen_random_uuid()",
          },
          {
            column_name: "role_id",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "permission_id",
            data_type: "uuid",
            is_nullable: "YES",
            column_default: null,
          },
        ],
      },
      {
        table_schema: "public",
        table_name: "roles",
        columns: [
          {
            column_name: "id",
            data_type: "uuid",
            is_nullable: "NO",
            column_default: "uuid_generate_v4()",
          },
          {
            column_name: "rolename",
            data_type: "text",
            is_nullable: "NO",
            column_default: null,
          },
        ],
      },
      {
        table_schema: "public",
        table_name: "shifts",
        columns: [
          {
            column_name: "shift_id",
            data_type: "uuid",
            is_nullable: "NO",
            column_default: "gen_random_uuid()",
          },
          {
            column_name: "shift_name",
            data_type: "character varying",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "start_time",
            data_type: "timestamp with time zone",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "end_time",
            data_type: "timestamp with time zone",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "buffer_start",
            data_type: "time without time zone",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "buffer_end",
            data_type: "time without time zone",
            is_nullable: "YES",
            column_default: null,
          },
        ],
      },
      {
        table_schema: "public",
        table_name: "users",
        columns: [
          {
            column_name: "id",
            data_type: "uuid",
            is_nullable: "NO",
            column_default: "uuid_generate_v4()",
          },
          {
            column_name: "name",
            data_type: "text",
            is_nullable: "NO",
            column_default: null,
          },
          {
            column_name: "created_at",
            data_type: "timestamp with time zone",
            is_nullable: "NO",
            column_default: "now()",
          },
          {
            column_name: "last_seen",
            data_type: "timestamp with time zone",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "password",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "role",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "verified",
            data_type: "boolean",
            is_nullable: "YES",
            column_default: "false",
          },
          {
            column_name: "location_ids",
            data_type: "ARRAY",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "isActive",
            data_type: "boolean",
            is_nullable: "YES",
            column_default: "true",
          },
          {
            column_name: "email",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "firstname",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "lastname",
            data_type: "text",
            is_nullable: "YES",
            column_default: null,
          },
          {
            column_name: "isResetRequested",
            data_type: "boolean",
            is_nullable: "NO",
            column_default: "false",
          },
          {
            column_name: "shift_ids",
            data_type: "ARRAY",
            is_nullable: "YES",
            column_default: null,
          },
        ],
      },
    ],
  },
};
